[package]
name = "dumb-container"
version = "0.0.2"
edition = "2021"
license = "MIT"
description = "A Vec-backed associative map"
repository = "https://github.com/schuelermine/dumb-container"
readme = "README.md"
