[package]
name = "simple-vec-collections"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Collections implemented using Vec"
repository = "https://github.com/schuelermine/simple-vec-collections"
readme = "README.md"
