[package]
name = "vec-map"
version = "0.0.1"
edition = "2021"
license = "MIT"
license-file = "LICENSE"
description = "A Vec-backed associative map"
repository = "https://github.com/schuelermine/vec-map"
readme = "README.md"
