[package]
name = "dumb-container"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "A Vec-backed associative map"
repository = "https://github.com/schuelermine/vec-map"
readme = "README.md"
