[package]
name = "simple-vec-collections"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "Collections implemented using Vec"
repository = "https://github.com/schuelermine/simple-vec-collections"
readme = "README.md"
rust-version = "1.65.0"
